"""Tests of the git hooks of `make hooks` (D-14, D-83).

Run: python3 -m unittest discover -s docs/tools -p 'test_*.py'
"""
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
PRE_COMMIT = os.path.join(ROOT, ".githooks", "pre-commit")
COMMIT_MSG = os.path.join(ROOT, ".githooks", "commit-msg")
TOOLS = ("git", "grep", "sed", "xargs", "cat", "dirname", "env")
IDENTITY = {"GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@example.com",
            "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@example.com"}


class CommitMessage(unittest.TestCase):
    def run_hook(self, message):
        with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False, encoding="utf-8") as handle:
            handle.write(message)
        self.addCleanup(os.unlink, handle.name)
        return subprocess.run(["sh", COMMIT_MSG, handle.name], capture_output=True, text=True)

    def test_conventional_subjects_pass(self):
        for message in ("docs: add the roadmap\n", "feat(api)!: drop the old route\n\nThe body.\n",
                        "fix(policy): round the load\n\nCo-Authored-By: A Person <person@example.com>\n",
                        "Merge branch 'main' into docs/x\n", 'Revert "docs: add the roadmap"\n',
                        "fixup! docs: add the roadmap\n", "# a comment line of git\ndocs: add the roadmap\n"):
            with self.subTest(message=message):
                out = self.run_hook(message)
                self.assertEqual(out.returncode, 0, out.stdout)

    def test_other_subjects_fail(self):
        for message in ("Add the roadmap\n", "docs:add the roadmap\n", "Docs: add the roadmap\n",
                        "feature: a thing\n", "docs(Roadmap): add\n", "\n"):
            with self.subTest(message=message):
                out = self.run_hook(message)
                self.assertEqual(out.returncode, 1, out.stdout)
                self.assertIn("Conventional Commits", out.stdout)

    def test_an_ai_co_author_fails(self):
        for trailer in ("Co-Authored-By: Claude Opus <noreply@anthropic.com>", "co-authored-by: Codex <codex@openai.com>",
                        "Co-authored-by: ChatGPT <x@y>", "  Co-Authored-By: GPT-6 <bot@example.com>"):
            with self.subTest(trailer=trailer):
                out = self.run_hook(f"docs: add the roadmap\n\nThe body.\n\n{trailer}\n")
                self.assertEqual(out.returncode, 1, out.stdout)
                self.assertIn("AI co-author", out.stdout)

    def test_a_generated_with_line_fails(self):
        for line in ("🤖 Generated with [Claude Code](https://claude.com/claude-code)", "Generated with Codex",
                     "Generated by an assistant", "This file was generated with ChatGPT."):
            with self.subTest(line=line):
                out = self.run_hook(f"docs: add the roadmap\n\n{line}\n")
                self.assertEqual(out.returncode, 1, out.stdout)
                self.assertIn("Generated with", out.stdout)

    def test_plain_words_about_generation_pass(self):
        out = self.run_hook("build(proto): regenerate the code\n\nThe code generated with buf stays committed.\n")
        self.assertEqual(out.returncode, 0, out.stdout)

    def test_a_comment_line_can_name_an_ai(self):
        out = self.run_hook("docs: add the roadmap\n# Co-Authored-By: Claude <noreply@anthropic.com>\n")
        self.assertEqual(out.returncode, 0, out.stdout)


class PreCommit(unittest.TestCase):
    """The hook runs with a PATH that holds the tools it needs, and a fake gh when a test asks for one."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.repo = os.path.join(self.tmp.name, "repo")
        self.bin = os.path.join(self.tmp.name, "bin")
        os.makedirs(os.path.join(self.repo, "docs", "tools"))
        os.makedirs(self.bin)
        for tool in TOOLS:
            found = shutil.which(tool)
            self.assertIsNotNone(found, tool)
            os.symlink(found, os.path.join(self.bin, tool))
        os.symlink(sys.executable, os.path.join(self.bin, "python3"))
        shutil.copy(os.path.join(HERE, "ste-check.py"), os.path.join(self.repo, "docs", "tools", "ste-check.py"))
        self.git("init", "-q", "-b", "main")
        self.write("README.md", "The app runs.\n")
        self.git("add", "-A")
        self.git("commit", "-q", "--no-verify", "-m", "chore: base")

    def tearDown(self):
        self.tmp.cleanup()

    def git(self, *args):
        env = {**os.environ, **IDENTITY}
        return subprocess.run(["git", *args], cwd=self.repo, capture_output=True, text=True, env=env, check=True)

    def write(self, path, text):
        full = os.path.join(self.repo, path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as handle:
            handle.write(text)

    def fake_gh(self, state):
        path = os.path.join(self.bin, "gh")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(f"#!/bin/sh\necho {state}\n")
        os.chmod(path, 0o755)

    def run_hook(self):
        env = {"PATH": self.bin, "HOME": self.tmp.name, **IDENTITY}
        return subprocess.run(["/bin/sh", PRE_COMMIT], cwd=self.repo, capture_output=True, text=True, env=env)

    def test_main_takes_no_commit(self):
        out = self.run_hook()
        self.assertEqual(out.returncode, 1, out.stdout)
        self.assertIn("main takes no commit", out.stdout)

    def test_a_branch_with_a_good_document_passes(self):
        self.git("switch", "-q", "-c", "docs/x")
        self.write("docs/a.md", "The app plans a workout.\n")
        self.git("add", "docs/a.md")
        out = self.run_hook()
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)

    def test_a_staged_document_that_fails_the_rules_fails(self):
        self.git("switch", "-q", "-c", "docs/x")
        self.write("docs/a b.md", "The plan should be written.\n")
        self.git("add", "docs/a b.md")
        out = self.run_hook()
        self.assertNotEqual(out.returncode, 0, out.stdout)
        self.assertIn("docs/a b.md:1: rule 3.2/3.4", out.stdout)

    def test_an_unstaged_document_takes_no_rule(self):
        self.git("switch", "-q", "-c", "docs/x")
        self.write("docs/a.md", "The plan should be written.\n")
        out = self.run_hook()
        self.assertEqual(out.returncode, 0, out.stdout)

    def test_a_merged_branch_takes_no_commit(self):
        self.git("switch", "-q", "-c", "docs/x")
        self.fake_gh("MERGED")
        out = self.run_hook()
        self.assertEqual(out.returncode, 1, out.stdout)
        self.assertIn("MERGED already", out.stdout)

    def test_an_open_branch_passes(self):
        self.git("switch", "-q", "-c", "docs/x")
        self.fake_gh("OPEN")
        self.assertEqual(self.run_hook().returncode, 0)

    def test_no_gh_fails_open(self):
        self.git("switch", "-q", "-c", "docs/x")
        self.assertFalse(os.path.exists(os.path.join(self.bin, "gh")))
        self.assertEqual(self.run_hook().returncode, 0)

    def test_git_runs_both_hooks_through_the_hooks_path(self):
        self.git("config", "core.hooksPath", os.path.join(ROOT, ".githooks"))
        self.git("switch", "-q", "-c", "docs/x")
        self.write("docs/a.md", "The app plans a workout.\n")
        self.git("add", "docs/a.md")
        env = {"PATH": self.bin, "HOME": self.tmp.name, **IDENTITY}
        bad = subprocess.run(["git", "commit", "-q", "-m", "Add a document"], cwd=self.repo, capture_output=True, text=True, env=env)
        self.assertEqual(bad.returncode, 1, bad.stdout + bad.stderr)
        good = subprocess.run(["git", "commit", "-q", "-m", "docs: add a document"], cwd=self.repo, capture_output=True, text=True, env=env)
        self.assertEqual(good.returncode, 0, good.stdout + good.stderr)


if __name__ == "__main__":
    unittest.main()
